name: Deploy with Git Commands

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Prepare deployment
        run: |
          # 保存构建输出到临时目录
          mkdir -p /tmp/out
          cp -r out/* /tmp/out/
          
          # 创建干净的gh-pages分支
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          
          # 复制保存的构建输出
          cp -r /tmp/out/* .
          touch .nojekyll
          
      - name: Commit and push
        run: |
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push -f origin gh-pages